flows:
  - envs:
     IOS_SCHEME: "newscheme"
     IOS_CONFIGURATION: "Release"
     IOS_EXPORT_METHOD: "ad-hoc"
     IOS_OUTPUT_DIR: "./ipa_dir"
     
    steps:
      - name: Git Clone
        scripts: |
          git clone ${FLOW_GIT_URL}
      
      - name: Build
        scripts: |
          fastlane gym --scheme ${IOS_SCHEME} --configuration ${IOS_CONFIGURATION} --export_method ${IOS_EXPORT_METHOD} --output_directory ${IOS_OUTPUT_DIR}
      
      - name: Print ipa
        scripts: |
          array=$(find ${IOS_OUTPUT_DIR} -name *.apk -o -name *.ipa 2>&1)
          for file in ${array[@]}
          do
            echo $file 
          done
